name: hoomd
dependencies:
- alabaster=0.7.8=py35_0
- babel=2.3.3=py35_0
- docutils=0.12=py35_2
- imagesize=0.7.1=py35_0
- jinja2=2.8=py35_1
- markupsafe=0.23=py35_2
- openssl=1.0.2h=1
- pip=8.1.2=py35_0
- pygments=2.1.3=py35_0
- python=3.5.1=0
- pytz=2016.4=py35_0
- readline=6.2=2
- setuptools=22.0.5=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx=1.4.1=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - sphinx-rtd-theme==0.1.9

